language: node_js
node_js:
  - "10"
  - "12"
cache:
  directories:
    - "node_modules"
before_script:
  - npm run build
script:
  - npm run test:coveralls
  - npm run lint:all
deploy:
  - provider: script
    skip_cleanup: true
    script: /bin/sh travis/uploadArchives.sh
    on:
      branch: master
      node_js: "10"
  - provider: script
    skip_cleanup: true
    script: /bin/sh travis/release.sh
    on:
      branch: $RELEASE_BRANCH
      node_js: "10"
